spring.jpa.show_sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
