spring:
  main:
    web-application-type: SERVLET
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
